on:
  push:
    branches:
      - "**"
    tags:
      - "v*"
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: test with tox
      run: tox
      env:
        PG_HOST: postgres

    - name: generate distributables
      run: |
        pip install wheel
        python setup.py sdist bdist_wheel
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    - name: publish to pypi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
